#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install trove guest python dependencies - see redstack functions_qemu

set -e
set -o xtrace

pip-python install pymongo>=3.0.2,!=3.1
