#!/bin/bash

set -e
set -o xtrace
export DEBIAN_FRONTEND=noninteractive

mkdir -p /opt/datastore_package/

# if datastore package location was a directory then lets
# extract the datastore_package.tgz into /opt/datastore_package directory
pushd /opt/datastore_package/
tar -xzf /tmp/in_target.d/datastore_package/datastore_package.tgz
popd
