#!/bin/bash

set -e
set -o xtrace
export DEBIAN_FRONTEND=noninteractive

mkdir -p /opt/datastore_package/

# if datastore package location was a directory then lets
# extract the datastore_package.tgz into /opt/datastore_package directory
if [ -f  /tmp/in_target.d/datastore_package/datastore_package.tgz ]
then
    pushd /opt/datastore_package/
    tar -xzf /tmp/in_target.d/datastore_package/datastore_package.tgz
    popd

else
    for package_file in `ls -1r /tmp/in_target.d/datastore_package/`
    do
        cp /tmp/in_target.d/datastore_package/${package_file} /opt/datastore_package/
    done
fi
