#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
echo "deb http://debian.datastax.com/community stable main" >> /etc/apt/sources.list.d/cassandra.sources.list
curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
apt-get update
apt-get install -qy openjdk-7-jdk expect python-dev
apt-get install -qy libxml2-dev ntp mc
apt-get install -qy libxslt1-dev python-pexpect
apt-get install -qy python-migrate build-essential
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
python ez_setup.py
wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
python get-pip.py
