#!/bin/sh

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" >> /etc/apt/sources.list.d/pgdg.list
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
apt-get update
apt-get upgrade -qy
apt-get -y install postgresql-9.3 pgadmin3
