#!/bin/sh

# This is an install.d phase script to setup hadoop.

cd /tmp

TMP_HOOKS_DIR="/tmp/in_target.d"

tar zxvf ${TMP_HOOKS_DIR}/hadoop-2.7.1.tar.gz

mv hadoop-2.7.1 /usr/local/hadoop

sudo chown -R hadoop.hadoop /usr/local/hadoop

sudo mkdir /var/log/hadoop
sudo chown -R hadoop.hadoop /var/log/hadoop

cd /home/hadoop

echo "export HADOOP_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc
echo "export HADOOP_LOG_DIR=/var/log/hadoop" >> /home/hadoop/.bashrc
echo "export PATH=$PATH:/usr/local/hadoop/bin" >> /home/hadoop/.bashrc

cd /usr/local/hadoop/etc/hadoop

cat > core-site.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<!--
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License. See accompanying LICENSE file.
-->

<!-- Put site-specific property overrides in this file. -->

<configuration>
    <property>
        <name>fs.defaultFS</name>
        <value>hdfs://localhost:9000</value>
    </property>
</configuration>
EOF

cat > hdfs-site.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<!--
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License. See accompanying LICENSE file.
-->

<!-- Put site-specific property overrides in this file. -->

<configuration>
    <property>
        <name>dfs.replication</name>
        <value>1</value>
    </property>

    <property>
        <name>dfs.name.dir</name>
        <value>/data/hdfs/name</value>
    </property>

    <property>
        <name>dfs.data.dir</name>
        <value>/data/hdfs/data</value>
    </property>

    <property>
        <name>dfs.heartbeat.interval</name>
        <value>3</value>
    </property>
</configuration>

EOF

chown hadoop.hadoop core-site.xml
chown hadoop.hadoop hdfs-site.xml

sed -i 's/export JAVA_HOME=${JAVA_HOME}/export JAVA_HOME=\/usr\/lib\/jvm\/java-7-openjdk-amd64\/jre/' \
    /usr/local/hadoop/etc/hadoop/hadoop-env.sh

echo "export HADOOP_LOG_DIR=/var/log/hadoop" >> /usr/local/hadoop/etc/hadoop/hadoop-env.sh
