#!/bin/bash

set -e
set -o xtrace

# CONTEXT: HOST prior to IMAGE BUILD as SCRIPT USER
# PURPOSE: Download the DB2 Express-C v10.5 packages to a directory on the local filesystem or
#          to a private repository. The download location is specified using the env variable:
#          DATASTORE_PKG_LOCATION

CURRENT_DIR=$(pwd)
DATASTORE_PKG_NAME=${DATASTORE_PKG_NAME:-v10.5_linuxx64_expc.tar.gz}

[ -n "${TMP_HOOKS_PATH}" ] || die "Temp hook path not set"

# First check if the package is available for download in a private repository.
# If not, then check the default directory to see if packages are available
# there.
if ! wget ${DATASTORE_DOWNLOAD_OPTS} ${DATASTORE_PKG_LOCATION}/${DATASTORE_PKG_NAME};
   then
      echo "Could not find a private repository to download DB2-Express-C packages from."
      echo "Trying the local filesystem."
      if [ -f ${DATASTORE_PKG_LOCATION}/${DATASTORE_PKG_NAME} ]
         then
             echo "Found the DB2 Express-C packages in ${DATASTORE_PKG_LOCATION}."
             dd if=${DATASTORE_PKG_LOCATION}/${DATASTORE_PKG_NAME} of=${TMP_HOOKS_PATH}/db2.tar.gz
         else
             echo "Unable to find the DB2 package in ${DATASTORE_PKG_LOCATION}."
             echo "Please register and download the DB2 Express-C packages to a private repository or local filesystem."
             exit -1
      fi
   else
     echo "Downloading the DB2 Express-C package from the private repository"
     dd if=${CURRENT_DIR}/${DATASTORE_PKG_NAME} of=${TMP_HOOKS_PATH}/db2.tar.gz
fi
