#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: take "staged" apt sources file and put them in the apt sources directory on the GUEST image

set -e
set -o xtrace

# Apt specific

