#!/bin/bash

set -e
set -o xtrace

# DB2_PKG_LOCATIOn points to the directory where the DB2 packages
# are located to install.
DB2_PKG_LOCATION="/db2"
DB2_PACKAGE_NAME="v10.5_linuxx64_expc.tar.gz"
mkdir ${DB2_PKG_LOCATION}
cd ${DB2_PKG_LOCATION}

# Copy the package from the temporary filesystem
dd if=/tmp/in_target.d/${DB2_PACKAGE_NAME} of=${DB2_PKG_LOCATION}/${DB2_PACKAGE_NAME}

tar -xvzf ${DB2_PACKAGE_NAME}
cd expc

# installing dependencies
apt-get install libaio1
apt-get install libstdc++5
apt-get install libstdc++6

# start the installation process. Accepts the default installation directory 'opt/ibm/db2/V10.5'
${DB2_PKG_LOCATION}/expc/db2_install -b /opt/ibm/db2/V10.5 -f sysreq -l ${DB2_PKG_LOCATION}/db2_install.log

# create the DB2 users.
# DB2 instance owner - db2inst1
# DB2 fence user - db2fenc1
# DB2 admin user - db2das1
useradd -m db2inst1
useradd -m db2fenc1
useradd -m db2das1

# During the DB2 server instance create process, it kept throwing an error
# saying that the hostname could not be resolved. Hence added the following
# line to /etc/hosts.
echo $(hostname -I | cut -d\  -f1) $(hostname) | sudo tee -a /etc/hosts

# Create the DB2 server instance
/opt/ibm/db2/V10.5/instance/db2icrt -a server -u db2fenc1 db2inst1
/opt/ibm/db2/V10.5/cfg/db2ln

# Configure DB2 server instance to communicate via TCP/IP on a particulat port.
echo 'db2c_db2inst1 50000/tcp # DB2 connection service port' >> /etc/services

# Configure DB2 to use the TCP/IP settings defined above.
su - db2inst1 -c "db2 update database manager configuration using svcename db2c_db2inst1"

# Start the actual TCP/IP communication.
su - db2inst1 -c "db2set DB2COMM=tcpip"
