#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

# avoid some dep conflicts here
yum -y remove mariadb-libs mariadb-server

# install vendor release repo
yum -y install http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm

# The fix to make versions of percona-xtrabackup > v2.2 work with Trove
# was put into the mysql guestagent code for Mitaka. There are no current
# plans to backport so we need to make sure the guest generated when the
# tests are run for Kilo or Liberty get the 2.2 verson of PXB
if [[ $BRANCH_OVERRIDE == "stable/kilo" || $BRANCH_OVERRIDE == "stable/liberty" ]]; then
    PXB_VERSION_OVERRIDE="-22"
fi

yum -y install socat
yum -y install Percona-XtraDB-Cluster-server-56 Percona-XtraDB-Cluster-client-56 \
	Percona-XtraDB-Cluster-galera-25 percona-xtrabackup${PXB_VERSION_OVERRIDE}

# not all mysql vendor packages add the
# includedir line to ALL its default confs;
# needs to be there for the config swaps
sed -i '/!includedir[ \t]*\/etc\/my.cnf.d/d' /etc/my.cnf
sed -i '$ a !includedir \/etc\/mysql\/conf.d' /etc/my.cnf

# move conf dir
mkdir /etc/mysql
mv /etc/my.cnf.d /etc/mysql/conf.d
chcon -Rv --type=mysqld_etc_t /etc/mysql

# cluster template unfortunately has an Ubuntu path
ln -s /usr/lib64/galera3/libgalera_smm.so /usr/lib/libgalera_smm.so

# sock file needs to be written here too
# but pre script sets mysql:mysql
chown -R mysql:root /var/lib/mysql

# ensure Trove manages the boostrap stuff (new wsrep cluster)
systemctl disable mysql@bootstrap
systemctl disable mysql
