#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Take "staged" DATASTORE_PKG_FILE (see extra-data.d/93-copy-vertica-deb)
# and put as /vertica.deb for guest usage.

set -e
set -o xtrace

TMP_HOOKS_DIR="/tmp/in_target.d"

if [ ! -z ${DATASTORE_PKG_FILE} ]; then
    dd if=${TMP_HOOKS_DIR}/${DATASTORE_PKG_FILE} of=/vertica.deb
else
    echo "DATASTORE_PKG_FILE is not set"
    exit -1
fi
