#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT - install.d
# PURPOSE: Install controller base required packages

set -e
set -o xtrace
export DEBIAN_FRONTEND=noninteractive

# Install base packages
apt-get install -qy build-essential bc iptables
apt-get install -qy curl sysstat pstack mcelog
apt-get install -qy python-dev g++ unixODBC unixODBC-dev

# Install Vertica package

# Copy the package file to the image,
#  as it needs to be used later during configuration.
# .deb package files need to be in the root directory for install_vertica script

for deb_file in `ls -1r /tmp/in_target.d/vertica/`
do
    cp /tmp/in_target.d/vertica/$deb_file /$deb_file
    dpkg -i /$deb_file
done

# Creating dbadmin user and verticadba group
groupadd verticadba
useradd -g verticadba -d /home/dbadmin -s /bin/bash -m dbadmin
echo "export PATH=/opt/vertica/bin:\$PATH" >> ~dbadmin/.profile
echo "export TZ=`date +%Z`" >>  ~dbadmin/.profile

# Create base directory for to be used for database creation
mkdir /var/lib/vertica
chown dbadmin:verticadba /var/lib/vertica

# Backup /etc/hosts
cp -p /etc/hosts /etc/hosts.bkp
