#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

# Mysql client is needed by guestagent to store its state into Trove database even in MongoDB-only deployment
apt-get -y install libmysqlclient18 mysql-client-5.5 mongodb
