#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

dnf -y install percona-toolkit Percona-Server-shared-56 Percona-Server-server-56 Percona-Server-test-56 Percona-Server-client-56 percona-xtrabackup-22
