#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install trove guest python dependencies - see redstack functions_qemu

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y install python-dev libxml2-dev libxslt1-dev python-setuptools python-pip python-sqlalchemy python-lxml \
    python-routes python-eventlet python-webob python-pastedeploy python-paste python-netaddr \
    python-httplib2 python-iso8601 python-pexpect python-mysqldb python-migrate

pip install extras python-novaclient python-swiftclient python-cinderclient oslo.config kombu>2.4.7 six babel python-heatclient
