#!/bin/bash

# Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y install sysstat mytop ntp lvm2 xfsprogs xfsdump policycoreutils libmysqlclient-dev