#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install basic services and applications

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y install sysstat mytop ntp lvm2 xfsprogs xfsdump policycoreutils libmysqlclient-dev