#!/bin/bash
# Add the stack user we recommend folk use.

set -e
set -o xtrace

if ! id -u ubuntu >/dev/null 2>&1; then
    echo "Adding ubuntu user"
    useradd -G admin -m ubuntu -s /bin/bash
    passwd ubuntu <<_EOF_
ubuntu
ubuntu
_EOF_
fi

