#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install trove guest python dependencies - see redstack functions_qemu

set -e
set -o xtrace

yum install -y python-devel libxml2-devel libxslt-devel python-setuptools \
    python-sqlalchemy python-lxml \
    python-routes python-eventlet python-webob \
    python-kombu python-paste-deploy python-paste python-netaddr \
    python-httplib2 python-iso8601 python-pip MySQL-python \
    python-migrate python-anyjson gcc pexpect

# pick up the requirements file left for us by
# extra-data.d/15-reddwarf-dep

TMP_HOOKS_DIR="/tmp/in_target.d"

pip install -q --upgrade -r ${TMP_HOOKS_DIR}/requirements.txt
