#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get install -qy curl
echo "deb http://debian.datastax.com/community stable main" >> /etc/apt/sources.list.d/cassandra.sources.list
curl -L http://debian.datastax.com/debian/repo_key | apt-key add -
add-apt-repository -y ppa:openjdk-r/ppa

apt-get update
apt-get install -y --force-yes openjdk-8-jre python-dev
apt-get install -y dsc22=2.2.* cassandra=2.2.*

# The Python Driver 2.0 for Apache Cassandra.
pip install cassandra-driver
# Sorted sets support for the Python driver.
pip install blist
