#!/bin/bash

# CONTEXT: GUEST during CONSTUCTION as ROOT
# PURPOSE: adds the reddwarf host as an apt repo to get so that the guest can get the conf file for mysql

set -e
set -o xtrace

source $_LIB/die

[ -n "$TMP_HOOKS_PATH." ] || die "Temp hook path not set"

cat ${REDSTACK_SCRIPTS}/files/apt_repo.list > ${TMP_HOOKS_PATH}/reddwarf-source-host.list
