#!/bin/bash

set -e
set -o xtrace

# CONTEXT: HOST prior to IMAGE BUILD as SCRIPT USER
# PURPOSE: creates the SSH key on the host if it doesn't exist.  Then this copies the keys over to a staging area where
# they will be duplicated in the guest VM.
# This process allows the host to log into the guest but more importantly the guest phones home to get the reddwarf
# source

source $_LIB/die

[ -n "$TMP_HOOKS_PATH." ] || die "Temp hook path not set"

[ -n "${HOST_USERNAME}" ] || die "HOST_USERNAME needs to be set to the user for the current user on the host"

if [ `whoami` = "root" ]; then
    die "This should not be run as root"
fi


generate_empty_passphrase_ssh_key () {
    echo "generating a empty passphrase DEV ONLY rsa key"
    SSH_DIR=$1
    expect -c "
spawn sudo -Hiu ${HOST_USERNAME} /usr/bin/ssh-keygen -f ${SSH_DIR}/id_rsa -q
expect \"empty for no passphrase\"
send \n
expect assphrase
send \n
expect eof"
}

add_host_key_to_authorizedkeys () {
    SSH_DIR=$1
    # test to see if the host key is already in its own authorized_keys file - if not then add it.  This is then later copied
    # to the guest image
    is_in_keyfile=`cat ${SSH_DIR}/id_rsa.pub | grep -f - ${SSH_DIR}/authorized_keys | wc -l`
    if [ $is_in_keyfile == 0 ]; then
        echo "Adding keyfile to authorized_keys, it does not yet exist"
        cat ${SSH_DIR}/id_rsa.pub >> ${SSH_DIR}/authorized_keys
    else
        echo "Keyfile already exists in authorized_keys - skipping"
    fi
}

HOME_DIR=/home/${HOST_USERNAME}
SSH_DIR=${HOME_DIR}/.ssh

if [ -e ${SSH_DIR} ]; then
    echo "${SSH_DIR} already exists"
else
    echo "Creating ${SSH_DIR} for ${HOST_USERNAME}"
    sudo -Hiu ${HOST_USERNAME} mkdir -p ${SSH_DIR}
fi

if [ ! -f ${SSH_DIR}/id_rsa.pub ]; then
    sudo apt-get -y install expect
    generate_empty_passphrase_ssh_key ${SSH_DIR}
fi

add_host_key_to_authorizedkeys ${SSH_DIR}

# copy files over the "staging" area for the guest image (they'll later be put in the correct location by the guest user
# not these keys should not be overridded otherwise a) you won't be able to ssh in and b) the guest won't be able to
# rsync the files
if [ -e ${SSH_DIR}/authorized_keys ]; then
   sudo -Hiu ${HOST_USERNAME} cat ${SSH_DIR}/authorized_keys > ${TMP_HOOKS_PATH}/ssh-authorized-keys
   sudo -Hiu ${HOST_USERNAME} cat ${SSH_DIR}/id_rsa > ${TMP_HOOKS_PATH}/id_rsa
   sudo -Hiu ${HOST_USERNAME} cat ${SSH_DIR}/id_rsa.pub > ${TMP_HOOKS_PATH}/id_rsa.pub
else
    die "SSH Authorized Keys file creation failed"
fi
