#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y install percona-toolkit percona-server-common-5.5  percona-server-server-5.5 percona-server-test-5.5  percona-server-client-5.5 percona-xtrabackup
