#!/bin/bash

# CONTEXT: HOST prior to IMAGE BUILD as SCRIPT USER
# PURPOSE: Stages the package installer file from DATASTORE_PKG_LOCATION,
# so that guest image has the package file.

set -e
set -o xtrace

source $_LIB/die

[ -n "$TMP_HOOKS_PATH" ] || die "Temp hook path not set"
[ -d "$DATASTORE_PKG_LOCATION" ] || die "Datastore package installer files not found at the directory:" $DATASTORE_PKG_LOCATION

mkdir $TMP_HOOKS_PATH/vertica

# remove the version number form the debian package name before copying
for vertica_file in `ls -1 $DATASTORE_PKG_LOCATION`
do
    if [[ $vertica_file == *".deb" ]]
    then
        package_name=$(basename "$vertica_file" ".deb")
        deb_file_name=`echo $package_name | cut -d "_" -f 1`
        cp $deb_file $TMP_HOOKS_PATH/vertica/$deb_file_name.deb
    else
        cp $vertica_file $TMP_HOOKS_PATH/vertica/$vertica_file
    fi
done
