#!/bin/bash

# CONTEXT: HOST prior to IMAGE BUILD as SCRIPT USER
# PURPOSE: stages the VERTICA_PACKAGE_FILE file, so that guest image has the package file.

set -e
set -o xtrace

source $_LIB/die

[ -n "$TMP_HOOKS_PATH." ] || die "Temp hook path not set"
dd if=${VERTICA_SOURCE}/${VERTICA_PACKAGE_FILE} of=${TMP_HOOKS_PATH}/${VERTICA_PACKAGE_FILE}
